////////////////////////////////////////////////////
// This is an AutoGenerated class created by Rocketlane for its Salesforce integration
// DO NOT EDIT OR DELETE THIS CLASS
////////////////////////////////////////////////////



trigger RLSTAGEWH7615SERVICESPROJECTC on Services_Project__c (after insert, after update, after delete, after undelete) {

    try {
        Integer integrationId = 7615;
        SObjectType sObjectType =  Services_Project__c.sObjectType;
        rocketlane.RlSystemTriggerContext triggerContext = new rocketlane.RlSystemTriggerContext();
        rocketlane.RlTriggerHandler.pushToRocketlane(integrationId, sObjectType, triggerContext);
    }
    catch(Exception e) {
        System.debug('RLSTAGEWH7615SERVICESPROJECTC - Exception when processing trigger: ' + e.getMessage());
        System.debug(e.getStackTraceString());
    }

}