////////////////////////////////////////////////////
// This is an AutoGenerated class created by Rocketlane for its Salesforce integration
// DO NOT EDIT OR DELETE THIS CLASS
////////////////////////////////////////////////////



trigger RLSTAGEWH7615ACCOUNT on Account (after insert, after update, after delete, after undelete) {

    try {
        Integer integrationId = 7615;
        SObjectType sObjectType =  Account.sObjectType;
        rocketlane.RlSystemTriggerContext triggerContext = new rocketlane.RlSystemTriggerContext();
        rocketlane.RlTriggerHandler.pushToRocketlane(integrationId, sObjectType, triggerContext);
    }
    catch(Exception e) {
        System.debug('RLSTAGEWH7615ACCOUNT - Exception when processing trigger: ' + e.getMessage());
        System.debug(e.getStackTraceString());
    }

}